export default {
  0: 'Mario',
  1: 'Fox',
  2: 'Cpt. Falcon',
  3: 'DK',
  4: 'Kirby',
  5: 'Bowser',
  6: 'Link',
  7: '???',
  8: 'Ness',
  9: 'Peach',
  10: 'Ice Climbers',
  11: 'Ice Climbers',
  12: 'Pikachu',
  13: 'Samus',
  14: 'Yoshi',
  15: 'Jigglypuff',
  16: 'Mewtwo',
  17: 'Luigi',
  18: 'Marth',
  19: 'Zelda',
  20: 'Young Link',
  21: 'Dr. Mario',
  22: 'Falco',
  23: 'Pichu',
  24: 'Mr. Game & Watch',
  25: 'Ganondorf',
  26: 'Roy'
};
